[build]
  base = "."
  publish = "static"         # Directory to publish static assets
  command = "pip install -r requirements.txt"  # Install dependencies

[functions]
  directory = "server"       # Directory containing serverless functions
  node_bundler = "esbuild"   # Faster bundling of Python functions
